package ua.antonfedoruk.zhfed_tgbot.botapi;

public enum BotState {
    WELCOME_NEW_CLIENT,
    CONTINUE_BEFORE_ABOUT_SUCCESS,
    CONTINUE_BEFORE_INTRODUCTION_VIDEO,
    CONTINUE_AFTER_INTRODUCTION_VIDEO,
    CONTINUE_BUTTONS,
    VIDEOS_CONCLUSION,
    CONSULTATION_AS_PRESENT,
    ABOUT_CONSULTATION,
    CONSULTATION_REQUEST,
    FILLING_CONSULTATION_DATA,
    ASK_CONSULTATION_MESSENGER,
    ASK_CONSULTATION_PHONE,
    ASK_CONSULTATION_COUNTRY,
    CONSULTATION_DATA_FILLED,
    SHOW_HELP_MENU,
    SHOW_MAIN_MENU,
    SHOW_EXIT_MENU,
    SHOW_NEWS_MENU
}