package ua.antonfedoruk.zhfed_tgbot.botapi;

public enum BotState {
    WELCOME_NEW_CLIENT,
    CONTINUE_BEFORE_ABOUT_SUCCESS,
    CONTINUE_BEFORE_INTRODUCTION_VIDEO,
    CONTINUE_AFTER_INTRODUCTION_VIDEO,
    CONTINUE_BUTTONS,
    VIDEOS_CONCLUSION,
    CONSULTATION_AS_PRESENT,
    ABOUT_CONSULTATION,
    CONSULTATION_REGISTRATION,
    CONSULTATION_REQUEST,
    ASK_CONSULTATION_COUNTRY,
    ASK_CONSULTATION_PHONE,
    ASK_CONSULTATION_MESSENGER,
    FILLING_CONSULTATION_DATA,
    _CONSULTATION_DATA_FILLED,
    WELCOME_NEW_CLIENT_COMPLETED,
    SHOW_HELP_MENU;
}
